name: Listener ARM Unit Test
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  search-target-runner:
    runs-on: [self-hosted, linux, X64, listener]
    outputs:
      output1: ${{ steps.step1.outputs.sha8 }}
    steps:
      - name: Get short SHA
        id: step1
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: search
        id: step2
        run: |
          cd /home/ec2-user/actions-runner
          echo $GITHUB_SHA
          sudo ./searchRunner.sh linux ARM64 ${{ steps.step1.outputs.sha8 }}
          retVal=$?
          if [ $retVal -eq 1 ]; then
              exit 1
          fi
  linux-arm64-unit-test:
    needs: search-target-runner
    runs-on: [self-hosted, linux, ARM64, '${{needs.search-target-runner.outputs.output1}}']
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.4
      - uses: actions/checkout@v2
        with:
          submodules: true
          path: src/github.com/aws/amazon-ecs-agent
      - name: make test
        run: |
          export GOPATH=$GITHUB_WORKSPACE