name: Linux Unit Tests
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  linux-X64-unit-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.4
      - uses: actions/checkout@v2
        with:
          submodules: true
          path: src/github.com/aws/amazon-ecs-agent
      - name: make test
        run: |
          export GOPATH=$GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE/src/github.com/aws/amazon-ecs-agent
          export CGROUP_PATH="/sys/fs/cgroup"
          make test-silent
          make analyze-cover-profile
  linux-arm64-unit-test:
    runs-on: [self-hosted, linux, ARM64, arm]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.4
      - uses: actions/checkout@v2
        with:
          submodules: true
          path: src/github.com/aws/amazon-ecs-agent
      - name: make test
        run: |
          export GOPATH=$GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE/src/github.com/aws/amazon-ecs-agent
          export CGROUP_PATH="/sys/fs/cgroup"
          make test-silent
          make analyze-cover-profile
