name: Windows 2019 Integration Test Suite
on:
  pull_request:
    types: [labeled]
jobs:
  windows-integ-test:
    if: ${{ github.event.label.name == 'bot\test' }}
    runs-on: [ self-hosted, Windows, '${{ matrix.arch }}', '${{ matrix.type }}' ]
    strategy:
      fail-fast: false
      matrix:
        type: [ win2019-full ]
        arch: [ X64 ]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.12
      - uses: actions/checkout@v2
        with:
          submodules: true
          path: src/github.com/aws/amazon-ecs-agent
      - name: run tests
        working-directory:
        run: |
          $Env:GOPATH = "$Env:GITHUB_WORKSPACE"
          cd "$Env:GITHUB_WORKSPACE"
          cd "src/github.com/aws/amazon-ecs-agent"
          .\scripts\run-integ-tests.ps1